import { useState, useEffect, useRef } from "react";
import TableOfContents from "@/components/TableOfContents";
import HeroSection from "@/components/HeroSection";
import ArticleSection from "@/components/ArticleSection";
import ImageLightbox from "@/components/ImageLightbox";
import ReadingProgress from "@/components/ReadingProgress";
import Footer from "@/components/Footer";
import AuthorBio from "@/components/AuthorBio";
import TopBar from "@/components/TopBar";
import Glossary from "@/components/Glossary";
import ConceptTag from "@/components/ConceptTag";
import ThemeToggle from "@/components/ThemeToggle";

export default function Home() {
  const [activeSection, setActiveSection] = useState("");
  const [lightboxImage, setLightboxImage] = useState<string | null>(null);
  const [lightboxAlt, setLightboxAlt] = useState("");
  const [tocOpen, setTocOpen] = useState(false);
  const mainRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        }
      },
      { rootMargin: "-20% 0px -60% 0px" }
    );

    const sections = document.querySelectorAll("section[id]");
    sections.forEach((section) => observer.observe(section));

    return () => observer.disconnect();
  }, []);

  const openLightbox = (src: string, alt: string) => {
    setLightboxImage(src);
    setLightboxAlt(alt);
  };

  return (
    <div className="min-h-screen bg-background text-foreground" ref={mainRef}>
      <ReadingProgress />
      <ThemeToggle />
      
      {/* Mobile TOC toggle */}
      <button
        onClick={() => setTocOpen(true)}
        className="fixed top-4 left-4 z-50 lg:hidden flex items-center gap-2 px-3 py-2 bg-card border border-border rounded-sm text-xs font-mono text-muted-foreground hover:text-foreground transition-colors shadow-sm"
        aria-label="Abrir índice"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <line x1="3" y1="6" x2="21" y2="6" />
          <line x1="3" y1="12" x2="21" y2="12" />
          <line x1="3" y1="18" x2="21" y2="18" />
        </svg>
        Índice
      </button>

      {/* Table of Contents - Sidebar */}
      <TableOfContents 
        activeSection={activeSection} 
        isOpen={tocOpen} 
        onClose={() => setTocOpen(false)} 
      />

      {/* Main Content */}
      <div className="lg:ml-64">
        {/* Top Bar with Audio + PDF */}
        <TopBar />

        <HeroSection />
        
        <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
          
          {/* Author Bio */}
          <AuthorBio />

          {/* ===================== SECCIÓN I: INTRODUCCIÓN ===================== */}
          <ArticleSection id="introduccion" number="I" title="Introducción">
            <p>Vivimos una revolución geopolítica y tecnológica que marcará las próximas décadas. Comprender esta <ConceptTag term="Doble Revolución" glossaryId="doble-revolucion" /> es vital para actuar de forma decisiva ante lo que viene.</p>
            <p>El desorden global y las fuerzas tectónicas que actualmente disputan el futuro del planeta exigen nuevos marcos analíticos capaces de captar la singularidad de esta época histórica. No nos enfrentamos a fenómenos políticos inconexos (como la visita de Trump a Pekín, la proliferación de conflictos internacionales o la disputa por las tierras raras), ni a simples avances técnicos (ya sean de Deepseek, Manus o Claude), sino a una mutación estructural más profunda. Para caracterizar esta mutación es clave analizar la convergencia histórica entre una <ConceptTag term="Revolución geopolítica" glossaryId="revolucion-geopolitica" /> marcada por la transición sistémica hacia la multipolaridad (representada por el ascenso y la agencia de China, BRICS y el Sur Global), y una <ConceptTag term="Revolución tecnológica" glossaryId="revolucion-tecnologica" /> impulsada por la inteligencia artificial y la robótica. Para describir esta convergencia propongo el concepto de "Doble Revolución". Esta Doble Revolución constituye el vector clave de transformación de las próximas décadas.</p>
            <p>Podemos datar el inicio de la Doble Revolución entre 2022 y 2023, cuando un conjunto de acontecimientos marcaron un punto de inflexión y aceleración sistémica. En el plano de la revolución tecnológica, el lanzamiento de ChatGPT y la popularización de los modelos de IA generativa, la tecnología que <a href="https://www.nature.com/articles/s41598-024-74406-4" target="_blank" rel="noopener noreferrer">más rápido se ha propagado</a> en la historia, coincidió con la ofensiva de Washington hacia Beijing, que restringió el acceso a semiconductores avanzados. En el plano de la revolución geopolítica, la guerra en Ucrania aceleró la fractura del orden euroatlántico. Los <a href="https://www.youtube.com/watch?v=N9Vhfp-DU9s" target="_blank" rel="noopener noreferrer">levantamientos del Sahel</a> cristalizaron en la llegada al poder de Ibrahim Traoré, con la expulsión de las fuerzas militares francesas. El genocidio en Gaza, perpetrado por Israel con el respaldo de Estados Unidos y la complicidad europea, mostró la violencia estructural del nuevo proyecto imperial del <a href="https://www.rosalux.de/en/news/id/54514/greater-israel-from-political-ideology-to-territorial-practice" target="_blank" rel="noopener noreferrer">Gran Israel</a>. Lejos de ser episodios aislados, estos hitos suponen erupciones simultáneas en las placas tectónicas del sistema-mundo.</p>
            <p>Para comprender la magnitud y naturaleza de este momento histórico, podemos apoyarnos en el trabajo del historiador marxista Eric Hobsbawm. En su obra <em>La era de las revoluciones, 1789-1848</em> Hobsbawm acuñó el término "Doble Revolución" para conceptualizar el proceso histórico que transformó el mundo moderno. Esta "Doble Revolución" del siglo XIX se caracterizó por la convergencia estructural de dos revoluciones simultáneas y entrelazadas: la <strong>Revolución Francesa</strong> –política e ideológica– y la <strong>Revolución Industrial inglesa</strong> –tecnológica y económica–. Ambas proporcionaron la base material (ferrocarriles, fábricas, proletariado) y la superestructural (liberalismo, nacionalismo, soberanía popular) para lo que fue, en palabras de Hobsbawm, "la mayor transformación de la historia humana desde los tiempos remotos en el que los hombres inventaron la agricultura y la metalurgia, la escritura, la ciudad y el estado".</p>
            <blockquote>
              Aunque surgieron en contextos nacionales distintos, estas transformaciones constituyeron "el doble cráter de un anchísimo volcán regional".
            </blockquote>
            <p>Juntas barrieron el antiguo Régimen feudal, sentando las bases del orden liberal burgués capitalista y consolidando las lógicas de dominación colonial. Este vasto y tumultuoso proceso generó contradicciones y fuertes resistencias internas – como el surgimiento del movimiento obrero y las corrientes socialistas — que marcaron los conflictos y las alternativas sociopolíticas, tecnológicas y económicas de los siglos XIX y XX.</p>
            <p>Así como la Doble Revolución del siglo XIX consolidó el orden capitalista occidental y su expansión imperialista –dejando al <ConceptTag term="Sur Global" glossaryId="sur-global" /> como espacio subordinado–, dos siglos después, la emergencia de potencias periféricas desafía activamente al hegemón en declive: un <ConceptTag term="Norte Global" glossaryId="norte-global" /> capitaneado con mano de hierro por EE.UU. El debilitamiento progresivo y relativo del bloque geopolítico occidental conlleva una transición conflictiva a un mundo multipolar y policéntrico. El investigador geopolítico Gabriel Merino considera que este proceso "significa una transformación estructural y revolucionaria y, como contracara, implica la caducidad del viejo ordenamiento político mundial y de las instituciones que cristalizaban las anteriores jerarquías de poder".</p>
            <p>La hipótesis de la Doble Revolución del XXI asume que nos encontramos ante el inicio de <strong>una erupción de magnitud comparable a la que tuvo lugar entre 1789 y 1848</strong>. Por un lado, la revolución geopolítica puede incluso llevarnos a una tercera guerra mundial o al fin de siglos de dominio occidental sobre el planeta. Por otro lado, la revolución de la IA y la robótica está transformando (y lo hará de forma mucho más radical en la próxima década) las bases materiales de las ciencias, la producción, el trabajo y la ley del valor.</p>
            <p>Las revoluciones tienen una geografía situada y desigual, y suelen tener diversos epicentros desde los que se propagan por dominación o por contagio, generando fenómenos complejos de poder y resistencia. Hobsbawm mostró cómo Europa fue el núcleo de la doble revolución del siglo XIX, a la que siguió el siglo americano, tras el periodo bipolar de la Guerra Fría. Hoy, como anticipó Giovanni Arrighi en su libro <em>Adam Smith en Pekín</em>, el siglo XXI está presenciando "el desplazamiento en curso del centro de la economía política global de Norteamérica a Asia Oriental". En esta misma línea, en la obra <em>China y el capitalismo global</em>, la teórica marxista Lin Chun sostiene que esta reconfiguración no replica la lógica imperialista, sino que articula una vía de desarrollo soberano donde el Estado chino busca, con sus límites y contradicciones, una trayectoria colectiva alternativa dentro y más allá del capitalismo tardío.</p>
            <p>Ante esta encrucijada histórica, donde convergen la transición del poder mundial y la disrupción tecnológica acelerada, se abren dos interrogantes fundamentales: ¿quiénes, cómo y para qué fines moldearán las fuerzas de la revolución tecnológica impulsada por la inteligencia artificial y la robótica? ¿Cuáles serán los sujetos políticos de la Doble Revolución del siglo XXI? Trataré de responder provisionalmente a estas preguntas a lo largo del texto.</p>
          </ArticleSection>

          {/* Infografía: Doble Revolución */}
          <figure 
            className="my-16 -mx-4 sm:-mx-6 lg:-mx-16 cursor-pointer group"
            onClick={() => openLightbox("/manus-storage/infinito_doble_revolucion_2bac6ba0.png", "La Doble Revolución: convergencia geopolítica y tecnológica")}
          >
            <img 
              src="/manus-storage/infinito_doble_revolucion_2bac6ba0.png" 
              alt="La Doble Revolución: convergencia geopolítica y tecnológica"
              className="w-full rounded-sm transition-transform duration-200 group-hover:scale-[1.005] shadow-lg"
            />
            <figcaption className="text-center text-sm text-muted-foreground mt-4 font-mono">
              Fig. 1 — La convergencia estructural de la Doble Revolución (2022-X)
            </figcaption>
          </figure>

          {/* ===================== SECCIÓN II ===================== */}
          <ArticleSection id="crisis-unipolaridad" number="II" title="Crisis de la unipolaridad y la fase hiper-imperialista">
            <p>El siglo XX estuvo marcado por la hegemonía geopolítica y tecnológica de EE.UU. Tras el final de la Segunda Guerra Mundial y el lanzamiento de las dos bombas atómicas, el poder estadounidense se consolidó en la Guerra Fría, con la imposición del Petrodólar en la década de los setenta y la posterior fase unipolar que siguió a la caída de la Unión Soviética. Esta fase unipolar se caracterizó por la ofensiva neoliberal, culminada con la extensión del dominio mundial del modelo tecnológico de Silicon Valley. En todos estos frentes, Washington logró proyectar una influencia indiscutible.</p>
            <p>No obstante, en el siglo XXI, este dominio unipolar atraviesa una <strong>crisis estructural</strong>, tal y como anticiparon teóricos del sistema-mundo como Immanuel Wallerstein y Giovanni Arrighi. Las economías occidentales han entrado en las últimas décadas en una fase de desindustrialización progresiva y financiarización acelerada, donde el capital se desvincula de la producción real. A esta decadencia material se le suman la sobreexpansión militar, la crisis institucional, y la pérdida de confianza en su moneda y de su legitimidad internacional. Más recientemente, como apunta Emmanuel Todd en su libro <em>La derrota de occidente</em>, la guerra en Ucrania ha exhibido a las claras "una crisis occidental, y más concretamente una crisis terminal estadounidense" que pone en riesgo la estabilidad global. Esta percepción de declive ya no es marginal: ha trascendido los círculos académicos y aparece con frecuencia en análisis de medios que van de The Economist a The <a href="https://www.nytimes.com/2026/05/03/opinion/iran-us-empire.html" target="_blank" rel="noopener noreferrer">New York Times</a>.</p>
            <p>Esta percepción del declive ha acelerado las estrategias de la Casa Blanca para contener el ascenso de China, a quien identifica como su rival sistémico. Esta dinámica se materializa en el intento de controlar los puntos de estrangulamiento geoestratégico; en la apropiación ilegal de recursos energéticos; y en la imposición de sanciones arbitrarias a los países insubordinados, como evidencia el bloqueo que lleva ya seis décadas sobre Cuba, el cerco sobre Venezuela, con el secuestro del presidente Nicolás Maduro. También se materializa en el inicio de guerras asimétricas, como en el caso de Irán, presiones coercitivas e intervenciones militares.</p>
            <blockquote>
              Gabriel Merino sostiene que nos encontramos ante una <a href="https://revistaeypp.flacso.org.ar/files/revistas/1730418327_31-56.pdf" target="_blank" rel="noopener noreferrer">"guerra mundial híbrida y fragmentada"</a>, un conflicto multifacético, donde la confrontación no se limita a lo militar, sino que incluye dimensiones económicas, informativas y tecnológicas, que operan a múltiples escalas y escenarios. Esta guerra híbrida es la forma central del conflicto en la transición de poder mundial, en la actual etapa de caos sistémico.
            </blockquote>
            <p>Paralelamente, el <a href="https://thetricontinental.org" target="_blank" rel="noopener noreferrer">Instituto Tricontinental</a> de investigación social, en un exhaustivo dossier, ha presentado otro marco analítico para leer geopolíticamente la situación, acuñando el concepto de <a href="https://thetricontinental.org/es/estudios-sobre-dilemas-contemporaneos-4-hiper-imperialismo/" target="_blank" rel="noopener noreferrer"><ConceptTag term="hiper-imperialismo" glossaryId="hiper-imperialismo" /></a>. Con esta fórmula define una nueva etapa del imperialismo, que emerge cuando el poder hegemónico ve mermada su capacidad productiva y financiera, a lo que responde fortaleciendo y concentrando poder militar. El dossier caracteriza al Norte Global como un bloque militar, político y económico, integrado por 49 países, entre ellos Estados Unidos, Reino Unido, Canadá, Australia, Nueva Zelanda, Israel, Japón y otros países de Europa Occidental y Oriental. En el ámbito militar, Turquía (como miembro de la OTAN), Corea del Sur y Filipinas (colonias militarizadas de facto de EE.UU.), son parte del "Bloque militar liderado por EE.UU.", aunque formen parte del Sur Global. Este bloque concentra el <strong>74,3% del gasto militar mundial</strong>. Esta estrategia multiplica los riesgos de escaladas militares regionales e incluso la confrontación nuclear. A pesar de ello, el dossier sitúa en el Sur Global un "nuevo estado de ánimo y un despertar del espíritu para hacer avanzar los proyectos incompletos de liberación nacional".</p>
          </ArticleSection>

          {/* ===================== SECCIÓN III ===================== */}
          <ArticleSection id="emergencia-sur-global" number="III" title="La emergencia del Sur Global y la Mayoría Global Multipolar">
            <p>En contraste con la arquitectura militarizada del Norte Global, el Sur Global no es un bloque militar sino un conjunto de países diversos subordinados dentro del sistema-mundo que representan a la mayoría de la población mundial. Está compuesto por 145 países, antes designados como "Tercer Mundo". Según el <a href="https://thetricontinental.org" target="_blank" rel="noopener noreferrer">Instituto Tricontinental</a>, este conjunto de naciones carece de una identidad común consensuada, aunque comparten que son "antiguas colonias o semicolonias del campo imperialista" y su "marginación histórica y contemporánea en el orden económico y político mundial". Siguiendo con el marco de Tricontinental se pueden identificar seis agrupaciones de países: socialistas independientes; con fuerte búsqueda de soberanía; nuevos no alineados; históricamente o actualmente progresistas; fuertemente militarizados por EE.UU.; y el Sur Global Diverso. Más allá de la heterogeneidad del Sur Global, los países BRICS+ han mostrado una notable capacidad productiva e industrial que contrasta con la financiarización de Occidente.</p>
            
            {/* Data highlight */}
            <div className="my-10 grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="border border-border p-5 text-center rounded-sm bg-card">
                <div className="font-mono text-3xl font-bold text-primary">41%</div>
                <div className="text-sm text-muted-foreground mt-1"><a href="https://www.imf.org/en/publications/weo/weo-database/2025/april" target="_blank" rel="noopener noreferrer">PIB mundial BRICS+ (PPA)</a></div>
              </div>
              <div className="border border-border p-5 text-center rounded-sm bg-card">
                <div className="font-mono text-3xl font-bold text-primary">3.900M</div>
                <div className="text-sm text-muted-foreground mt-1"><a href="https://www.worldometers.info/world-population/" target="_blank" rel="noopener noreferrer">Población BRICS+</a></div>
              </div>
              <div className="border border-border p-5 text-center rounded-sm bg-card">
                <div className="font-mono text-3xl font-bold text-primary">3,7%</div>
                <div className="text-sm text-muted-foreground mt-1"><a href="https://www.hinrichfoundation.com/research/how-to-use-it/economic-development/world-bank-group-economic-prospects-january-2026" target="_blank" rel="noopener noreferrer">Crecimiento anual vs 1,1% G7</a></div>
              </div>
            </div>

            <p>En 2026, los países de BRICS+ (Brasil, Rusia, India, China, Sudáfrica, Egipto, Etiopía, Irán, Emiratos Árabes Unidos, Indonesia y Arabia Saudita), representan ya el 41% del PIB mundial en términos de paridad de poder adquisitivo, superando con claridad el 28% del G7. El <a href="https://www.hinrichfoundation.com/research/how-to-use-it/economic-development/world-bank-group-economic-prospects-january-2026" target="_blank" rel="noopener noreferrer">crecimiento promedio</a> (mayo de 2026) de las naciones BRICS+ lo encabeza India, con un 6,2%, y China, con un 4,4%. De media, los BRICS+ crecieron un 3,7% en términos anuales, más del triple que las potencias occidentales, que crecieron 1,1%. A este peso económico se le suma un peso demográfico incontestable: los 11 países BRICS+ agrupan cerca de <a href="https://www.worldometers.info/world-population/" target="_blank" rel="noopener noreferrer">3.900 millones de personas</a>, es decir, entre el 45 y 50% de la población mundial. Si consideramos el Sur Global en su totalidad, este agrupa aproximadamente el 85% de la población mundial, frente al 15% de la población del Norte Global.</p>
            <p>Sin embargo, los BRICS+ no constituyen un bloque homogéneo ni una alianza ideológica cohesionada. Se trata más bien de una asociación pragmática y económica que agrupa intereses, sistemas políticos y visiones civilizatorias distintas, lo que genera contradicciones internas y límites en su articulación estratégica; como se ha puesto de manifiesto en el caso de la guerra contra Irán. A pesar de estas heterogeneidades, BRICS avanza, quizás lentamente, en construir una autonomía estructural y un ordenamiento más justo en el panorama internacional. Esta voluntad se materializa no solo en la demanda de reformar la ONU y ampliar el Consejo de Seguridad con asientos permanentes para Brasil, India y Sudáfrica, sino, sobre todo, en la construcción de una arquitectura financiera alternativa. En ese sentido, el <a href="https://www.ndb.int/" target="_blank" rel="noopener noreferrer">Nuevo Banco de Desarrollo (NDB)</a>, presidido por Dilma Rousseff, es una de las herramientas más importantes en la promoción activa del comercio en monedas nacionales, la promoción del desarrollo y el avance de los países BRICS+ hacia una desdolarización, que blinde sus economías frente a sanciones unilaterales.</p>
            <p>Pero la multipolaridad no es cosa exclusiva de los gobiernos. En la cumbre BRICS+ de Río de Janeiro en 2025, se institucionalizó el <a href="https://bricscouncil.ru/pt/events/v-brazilii-proshel-narodniy-sammit-briks" target="_blank" rel="noopener noreferrer"><strong>Consejo Popular de los BRICS+</strong></a>, como espacio donde 120 organizaciones populares del Sur Global, entre ellas el Movimiento Sin Tierra o la Marcha Mundial de Mujeres, presentaron directamente sus demandas en el contexto de la cumbre de jefes de Estado, lo que se reflejó en la declaración final. Esta intersección prometedora entre BRICS+ y organizaciones populares muestra algo más profundo: que la reconfiguración del poder mundial precisa de la convergencia entre proyectos estatales soberanos y luchas populares para configurar, por abajo, la orientación de la transición sistémica.</p>
            <blockquote>
              Sin estados soberanos, las organizaciones populares corren el riesgo de verse subyugadas por el poder imperial. Sin organización popular, la multipolaridad corre el riesgo de no superar las desigualdades del viejo orden. Cuanta más influencia de movimientos y más peso popular, más transformadora será la multipolaridad.
            </blockquote>
            <p>En esta intersección es donde requerimos del concepto de <strong>Mayoría Global Multipolar</strong> para designar un bloque histórico transnacional en formación, compuesto por Estados soberanos del Sur Global, bloques regionales como los BRICS+, clases populares, movimientos sociales, migrantes y sectores críticos del Norte Global que rechazan el hiperimperialismo actual y buscan construir un orden mundial multipolar, soberano, cooperativo y socialmente justo. No es un sujeto homogéneo ni una alianza puramente estatal, sino una constelación multiescalar donde convergen luchas y redes antiimperialistas, sociales, feministas, ecológicas, antirracistas, municipalistas, tecnológicas y culturales. Su potencial emancipador depende de que su articulación impulse el proceso de transición hacia la multipolaridad hacia planteamientos más transformadores, de justicia social y económica norte-sur, democratización tecnológica, transición ecológica, equidad de género y poder popular.</p>
            <p>La Mayoría Global Multipolar surge de una larga historia de despojo, colonialidad y explotación, pero también de la experiencia de resistencia y comunidad. Es el resultado histórico, pasado y presente de la lucha contra el imperialismo, el capitalismo y el colonialismo, heredera del espíritu que va de <a href="https://thetricontinental.org/es/dossier-conferencia-de-bandung/" target="_blank" rel="noopener noreferrer">Bandung</a> a la <a href="https://thetricontinental.org/es/ospaaal-history-spain/" target="_blank" rel="noopener noreferrer">Tricontinental</a>, como ha mostrado el teórico Vijay Prashad en sus obras <em>Naciones oscuras</em> e <em>Historia popular del Tercer Mundo</em>. La preocupación principal actual de la Mayoría Global Multipolar es el avance del genocidio y el hiperimperialismo, que amenazan el planeta con proyectos de viejos y nuevos imperios. En el plano digital, los movimientos tecnopolíticos que defienden la soberanía digital popular, el software y los modelos abiertos, tienen como adversario directo el poder de los tecno-oligarcas, el colonialismo de datos y el viraje securitario y de militarización de la IA. La Mayoría Global Multipolar es el sujeto histórico en formación de la Doble Revolución del siglo XXI, como el proletariado lo fue en la Doble Revolución del siglo XIX. Se forjará en crudas batallas por la dignidad humana y en la práctica de un nuevo internacionalismo antiimperialista.</p>
          </ArticleSection>

          {/* Infografía: Mayoría Global Multipolar */}
          <figure 
            className="my-16 -mx-4 sm:-mx-6 lg:-mx-16 cursor-pointer group"
            onClick={() => openLightbox("/manus-storage/mayoria_global_3d1decd7.png", "Mayoría Global Multipolar: componentes y articulación")}
          >
            <img 
              src="/manus-storage/mayoria_global_3d1decd7.png" 
              alt="Mayoría Global Multipolar: componentes y articulación"
              className="w-full rounded-sm transition-transform duration-200 group-hover:scale-[1.005] shadow-lg"
            />
            <figcaption className="text-center text-sm text-muted-foreground mt-4 font-mono">
              Fig. 2 — Mayoría Global Multipolar: bloque histórico transnacional en formación
            </figcaption>
          </figure>

          {/* ===================== SECCIÓN IV ===================== */}
          <ArticleSection id="revolucion-geopolitica" number="IV" title="La revolución geopolítica. Guerra y el triángulo multipolar">
            <p>El primer eje de la Doble Revolución es la revolución geopolítica: la transición sistémica de la unipolaridad estadounidense hacia un mundo policéntrico. Se puede definir como un proceso de insubordinación múltiple contra el poder unipolar estadounidense. Esta dinámica se manifiesta en un conjunto de acontecimientos: en el crecimiento y fortalecimiento de las capacidades de una parte de las naciones del Sur Global; en la resistencia iraní, sus potentes efectos en el mundo árabe y el nuevo estatus del Estrecho de Ormuz; en la articulación financiera de los BRICS+; en el proceso de desdolarización de la economía mundial; en las luchas antiimperialistas en América Latina, África y Asia; en la caída global de popularidad, posterior al 7 de octubre de 2023, de los aliados anglosionistas. Todos estos acontecimientos muestran la disputa por la orientación de la transición sistémica.</p>
            <p>Dentro de este proceso, <strong>China tiene un papel relevante, ya que es el nodo donde convergen la revolución tecnológica y la revolución geopolítica</strong>. Desde la revolución de 1949 liderada por Mao Zedong y las reformas de Deng Xiaoping a partir de 1978, China ha protagonizado, bajo el modelo de socialismo con características chinas, la mayor reducción de la pobreza de la historia humana: <a href="https://www.worldbank.org/en/news/press-release/2022/04/01/lifting-800-million-people-out-of-poverty-new-report-looks-at-lessons-from-china-s-experience?spm=a2ty_o01.29997173.0.0.50ee55fbDhnPdA" target="_blank" rel="noopener noreferrer">800 millones de personas</a>. En apenas cuatro décadas, el país transitó de ser una de las naciones más empobrecidas del mundo (tras el siglo de la humillación) a convertirse en la segunda economía mundial y la primera potencia industrial global. Al mismo tiempo, lejos de seguir una lógica expansionista tradicional, Pekín se ha mantenido firme en su doctrina del <strong>ascenso pacífico</strong> y una política exterior de no injerencia. Un dato que ilustra esta trayectoria es que desde el conflicto fronterizo con Vietnam en 1979, China no ha iniciado ni librado ninguna guerra ofensiva. Su estrategia se ha centrado en la cooperación Sur-Sur, articulada a través del ambicioso proyecto de la Franja y la Ruta, iniciativa orientada a crear corredores de conectividad (puertos, carreteras, redes 5G) con la participación de más de 150 países.</p>
            <p>Ante las crisis estructurales del orden internacional contemporáneo, el presidente chino Xi Jinping formalizó la visión de <a href="https://www.chinadaily.com.cn/a/202309/26/WS65124140a310d2dce4bb7dce.html" target="_blank" rel="noopener noreferrer">"construir una comunidad de futuro compartido para la humanidad"</a>, desplegada a través de un conjunto de propuestas normativas e institucionales: las Iniciativas de Desarrollo Global (2021), Seguridad Global (2022), Civilización Global (2023) y <a href="https://www.fmprc.gov.cn/eng/xw/wjbxw/202509/t20250901_11699912.html" target="_blank" rel="noopener noreferrer">Gobernanza Global</a> (2025), complementadas por la propuesta de Gobernanza de la Inteligencia Artificial. Estos marcos, fundamentados en los principios de la Carta de la ONU, buscan reformar y perfeccionar el sistema de gobernanza global ampliando la representación y la voz de los países en desarrollo bajo cinco principios rectores: igualdad soberana, respeto al derecho internacional, multilateralismo, enfoque centrado en el pueblo y acción concreta orientada a resultados. Si bien han cosechado una recepción favorable entre estados del Sur Global, en el Norte Global han pasado desapercibidos, cuando no han sido mirados con desconfianza.</p>
            <p>El ascenso de China y BRICS se ha convertido en la obsesión estratégica de la Casa Blanca y en este marco deben entenderse los conflictos y guerras actuales. El conflicto prolongado en Ucrania, el genocidio en Gaza o la guerra asimétrica que libra el eje estadounidense-israelí contra Irán y el Eje de la Resistencia son, en esencia (como sostiene el analista geopolítico brasileño Pepe Escobar) guerras contra la multipolaridad emergente. Estas no son disputas regionales aisladas, sino guerras contra el Sur Global. Son operaciones para fracturar la articulación soberana entre China, Rusia e Irán, tratando de impedir la consolidación del <strong>triángulo multipolar euroasiático</strong>. Sin embargo, lejos de fragmentar esta alianza, el ataque contra Irán ha hecho emerger con fuerza no solo las capacidades de Irán, sino que también ha intensificado la articulación entre estas tres naciones. Este triángulo estratégico es el pivote clave del mundo multipolar actual, un espacio donde el poder militar, económico, tecnológico e ideológico de Occidente no puede dominar. La asociación cada vez más integral entre Pekín, Moscú y Teherán supone, de facto, el bloque de contención más formidable contra el hiperimperialismo estadounidense y el proyecto del Gran Israel.</p>
            <p>Pero la revolución geopolítica no se reduce a la acción de los estados soberanos insubordinados al régimen de guerra imperial, sino que está actuando en múltiples frentes entre 2022 y 2026. En el combate contra el genocidio del pueblo palestino; en la lucha de este por su liberación nacional; en las <a href="https://globalsumudflotilla.org/es/" target="_blank" rel="noopener noreferrer">Flotillas de la libertad</a> que demuestran que el internacionalismo está en auge; en la resistencia iraní y del eje de la resistencia frente a la agresión de la "coalición Epstein". En África, en los levantamientos populares y <a href="https://thetricontinental.org/es/dossier-sahel-alianza-soberania/" target="_blank" rel="noopener noreferrer">la alianza de estados del Sahel</a> (Níger, Mali y Burkina Faso), que expresan el hartazgo de décadas de colonialismo francés. A esta ola se suman las protestas juveniles como <a href="https://thetricontinental.org/es/pan-africa/una-mujer-en-las-maandamano/" target="_blank" rel="noopener noreferrer">Maandamano</a> en Kenia, el movimiento campesino <a href="https://www.mviwata.or.tz/" target="_blank" rel="noopener noreferrer">MVIWATA</a> en Tanzania, que articula soberanía alimentaria y defensa de la tierra; y el sindicalismo combativo de <a href="https://www.numsa.org.za/about/" target="_blank" rel="noopener noreferrer">NUMSA</a> en Sudáfrica, el mayor sindicato de la clase trabajadora de todo el continente. En América Latina, con las luchas de los movimientos indígenas y campesinos, como las revueltas en <a href="https://www.telesurtv.net/bolivia-movilizaciones-rodrigo-paz-escala-segunda-semana/" target="_blank" rel="noopener noreferrer">Bolivia</a>, como en las luchas del <a href="https://camposenmovimiento.wixsite.com/camposenmovimiento/movimiento-afro-norte-del-cauca" target="_blank" rel="noopener noreferrer">Cauca</a> colombiano o el <a href="https://mst.org.br/" target="_blank" rel="noopener noreferrer">Movimiento Sin Tierra</a> brasileño, que, junto a <a href="https://viacampesina.org/es/" target="_blank" rel="noopener noreferrer">Vía Campesina</a>, llevan años construyendo soberanía alimentaria y poder popular. Con las <a href="https://www.industriall-union.org/es/india-se-movilizan-300-millones-de-trabajadores-y-trabajadoras/" target="_blank" rel="noopener noreferrer">huelgas</a> de más de 250 millones de trabajadores y campesinos en la India. Con los <a href="https://www.youtube.com/watch?v=bf8cY1j7-2A&t=5360s" target="_blank" rel="noopener noreferrer">movimientos en Okinawa (Japón), Taiwán, Filipinas, Corea del Sur o Vietnam</a> contra el militarismo y las bases norteamericanas en Asia.</p>
            <p>En el Norte Global, con las luchas de los movimientos antirracistas como <a href="https://regularizacionya.com/" target="_blank" rel="noopener noreferrer">Regularización Ya</a> para acceder a los derechos básicos; las movilizaciones contra el genocidio como la <a href="https://www.elsaltodiario.com/italia/una-historica-huelga-general-italia-guerra-palestina" target="_blank" rel="noopener noreferrer">huelga general salvaje en Italia</a>, la <a href="https://www.elsaltodiario.com/madrid/despliegue-policial-maximo-sofocar-protestas-propalestina-ultima-etapa-vuelta-madrid" target="_blank" rel="noopener noreferrer">interrupción de la vuelta ciclista</a> o las acciones directas de <a href="https://global.palestineaction.org/" target="_blank" rel="noopener noreferrer">Palestine Action</a>, los movimientos urbanos contra el rentismo y el <a href="https://sindicatdellogateres.org/es/" target="_blank" rel="noopener noreferrer">precio abusivo de los alquileres</a>; las luchas feministas, como la del reconocimiento del trabajo de cuidados o contra las violencias machistas digitales; las luchas contra el devenir autoritario de las sociedades del Norte Global como las protestas contra la <a href="https://www.democracynow.org/es/2026/2/2/titulares/more_than_300_anti_ice_protests_held_across_the_country" target="_blank" rel="noopener noreferrer">brutalidad del ICE</a> o las movilizaciones masivas contra Trump de la campaña <a href="https://www.nokings.org/" target="_blank" rel="noopener noreferrer">No Kings</a>.</p>
            <blockquote>
              La revolución geopolítica, en este sentido, es también la intensificación de la lucha de clases y pueblos a nivel mundial.
            </blockquote>
            <p>La aceleración de la revolución geopolítica multipolar pasa por la fortaleza de las luchas sociales y por el posicionamiento de estas en un contexto de guerra y militarización de las sociedades. En el Norte Global, los movimientos tienen la oportunidad de empujar hacia la ruptura del eje militar imperialista, especialmente en Europa para propiciar una tercera posición autónoma y bisagra con el Sur Global.</p>
          </ArticleSection>

          {/* ===================== SECCIÓN V ===================== */}
          <ArticleSection id="revolucion-tecnologica" number="V" title="La revolución tecnológica. Modelos asimétricos de IA">
            <p>La segunda dimensión de la Doble Revolución es la <strong>revolución tecnológico-productiva</strong> que representan la inteligencia artificial, la computación a gran escala y el avance de la robótica. Lejos de constituir un avance aislado, este proceso opera como un paradigma tecnoeconómico en el sentido de <a href="https://economiapoliticafeunam.wordpress.com/wp-content/uploads/2019/02/revoluciones-tecnologicas-y-capital-financiero-carlota-perez-1.pdfparte1y2-1.pdf" target="_blank" rel="noopener noreferrer">Carlota Pérez</a>: tras una fase de instalación financiera y especulativa, comienza a reconfigurar las bases materiales de la producción, el trabajo y la organización social.</p>
            <p>La IA puede entenderse como la maduración extrema de la quinta ola tecnológica –la revolución de la información y las telecomunicaciones–, pero también como el umbral de una posible sexta ola post-informacional. Los avances en IA acortan drásticamente los ciclos iterativos de las revoluciones tecnológicas precedentes y propulsan múltiples efectos sistémicos que todavía son difíciles de calibrar. Una novedad sustancial respecto de otras oleadas anteriores es la gran velocidad evolutiva de la revolución tecnológica actual, caracterizada por una <strong>aceleración recursiva</strong>. La inteligencia artificial no funciona como un sector productivo más, sino como una tecnología de propósito general e infraestructura cognitiva transversal que potencia, entrelaza y comprime el tiempo de desarrollo de campos emergentes como la computación cuántica, la robótica avanzada, la biotecnología o la genómica.</p>
            <p>Durante décadas, la revolución digital fue monopolizada por Estados Unidos y exportada internacionalmente, derivando en lo que Nick Srnicek describió como <a href="https://www.academia.edu/79849936/Capitalismo_de_Plataforma_Nick_Srnicek" target="_blank" rel="noopener noreferrer">"capitalismo de plataforma"</a>. Las Big Tech se han erigido como líderes de un modelo de acumulación en el que la extracción masiva de datos opera como materia prima fundamental, configurando –como advierte <a href="https://www.marcialpons.es/libros/teoria-de-la-dependencia-digital/9789878272481/" target="_blank" rel="noopener noreferrer">Cecilia Rikap</a>– un renovado mapa de dependencias y periferias digitales que reproduce las asimetrías del sistema-mundo.</p>
            <p>El modelo de Silicon Valley está mutando hacia formas más agresivas de integración con el aparato militar estadounidense. En enero de 2026, el <a href="https://defensescoop.com/2026/01/30/dod-cto-critical-technology-areas-emil-michael-cta-appointees/" target="_blank" rel="noopener noreferrer">Pentágono nombró a seis ejecutivos del sector digital para liderar sus áreas críticas de tecnología</a>. Al mismo tiempo, <a href="https://www.aljazeera.com/news/2026/5/1/pentagon-announces-deal-with-seven-ai-companies-for-classified-systems" target="_blank" rel="noopener noreferrer">investigaciones periodísticas</a> aseguran que los sistemas de IA de Anthropic y OpenAI fueron utilizados en la guerra de Irán en 2026, alimentando el debate sobre el giro militarista del Valle del Silicio. Pero si hay una empresa que representa <a href="https://www.authoritarian-stack.info/" target="_blank" rel="noopener noreferrer">el giro autoritario del stack</a> norteamericano, es <strong>Palantir Technologies</strong>. La empresa fundada por Peter Thiel opera como núcleo cohesivo, de vanguardia del <ConceptTag term="tecnoimperialismo" glossaryId="tecnoimperialismo" /> y como bisagra estratégica entre Israel y EE.UU., con presencia en 19 países, mayoritariamente aliados de la OTAN, incluida España. Palantir ha operado como una infraestructura de muerte para el ejército israelí en el genocidio en Gaza (como ha relatado el sociólogo <a href="https://tecnopolitica.blog.br/" target="_blank" rel="noopener noreferrer">Sergio Amadeu</a> en su libro <em>Guerra Total: IA y el complejo militar dataficado</em>) y en las acciones del ejército estadounidense en la guerra contra Irán. En su reciente manifiesto, la empresa exhibe sin pudor su supremacismo, menospreciando a otras naciones, presentando la inteligencia artificial como una "nueva arma de disuasión atómica", convocando a todo Silicon Valley a tomar partido en la dinámica hiperimperialista actual.</p>
            <p>No obstante, el monopolio tecnológico norteamericano se ha quebrado. Como muestra Gabriel Merino en su inspirador artículo <a href="https://revistas.unlp.edu.ar/CTyP/article/view/19068" target="_blank" rel="noopener noreferrer">"Los BRICS y la revolución tecno-productiva en la transición de sistema mundial"</a>, los países BRICS lideran tanto en número de publicaciones científicas mundiales (China copa el 20%) como en la generación de talento STEM, donde China e India ocupan la primera y la segunda posición y representan el 20% de la inversión global en I+D. A partir de estos datos, Merino define "el escenario geopolítico mundial como de multipolaridad relativa con ciertos rasgos bipolares en materia tecnológica, por el peso de Estados Unidos y China". En esta competencia de rasgos bipolares, la irrupción tecnológica china ha desbaratado cualquier ilusión unipolar. Según un informe del <a href="https://www.aspi.org.au/report/aspis-two-decade-critical-technology-tracker/" target="_blank" rel="noopener noreferrer">Instituto Australiano de Política Estratégica (ASPI)</a>, mientras que entre 2003 y 2007 EE.UU. lideraba en 60 de 64 tecnologías críticas, en el periodo 2019-2023 <strong>China ha pasado a liderar 57 de las 64 categorías analizadas</strong>. Según el investigador <a href="https://ihu.unisinos.br/categorias/159-entrevistas/658898-ia-vies-centrado-no-ocidente-representa-ameaca-direta-a-seguranca-cultural-e-nacional-da-china-e-do-sul-global-entrevista-especial-com-jeff-xiong" target="_blank" rel="noopener noreferrer">Jeff Xiong</a>, China "alcanzó una independencia relativa en la <ConceptTag term="soberanía digital" glossaryId="soberania-digital" /> hace cinco años". Respecto al crecimiento de las capacidades tecnocientíficas de los países BRICS, Xiong asegura que "nos enfrentamos a dificultades estructurales en el proceso de lograr la soberanía digital. El primer desafío es la alta dependencia de la infraestructura digital proporcionada por Estados Unidos". Por ello, sitúa la soberanía digital como un terreno clave para el Sur Global en las próximas décadas. Xiong sugiere que "las empresas chinas y los países del Sur Global deben coconstruir una nueva infraestructura digital y también desarrollar y explorar las metodologías de los gobiernos que unan la experiencia china con las realidades locales".</p>

            {/* Data highlight */}
            <div className="my-10 border-l-4 border-primary pl-6 py-4 bg-card rounded-r-sm">
              <div className="font-mono text-sm text-primary mb-2">ASPI — Tecnologías críticas</div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="text-2xl font-bold text-foreground">60/64</div>
                  <div className="text-sm text-muted-foreground">EE.UU. lideraba (2003-2007)</div>
                </div>
                <div>
                  <div className="text-2xl font-bold text-primary">57/64</div>
                  <div className="text-sm text-muted-foreground">China lidera (2019-2023)</div>
                </div>
              </div>
            </div>

            <p>Para comprender la naturaleza de esta batalla, resulta clave recuperar el concepto marxista de Intelecto General. En los <em>Grundrisse</em>, Marx anticipó que el sistema de máquinas y el conocimiento social acumulado se convertirían, al superar un umbral crítico, en fuerza productiva directa. En la era de la computación a gran escala, la inteligencia artificial y el avance de la automatización, el intelecto general podría renombrarse como <ConceptTag term="Intelecto Computacional" glossaryId="intelecto-computacional" />. Está compuesto por el conocimiento social acumulado materializado en los sistemas de máquinas de inteligencia artificial, datos, redes, algoritmos, infraestructuras digitales, trabajo tecnocientífico y la cooperación social distribuida bajo la figura marxiana del trabajador colectivo. Por tanto, la IA expresa la materialización histórica de siglos de trabajo cognitivo, datos colectivos, lucha contra la automatización y saberes populares procesados y estandarizados algorítmicamente.</p>
            <blockquote>
              El Intelecto Computacional es objeto de disputa tecnopolítica: bajo una lógica tecnoimperial se alinea con la acumulación privada, la guerra y el control algorítmico, pero bajo una lógica de reapropiación social se puede convertir en recurso para comunidades en lucha, fuente de desarrollo de nuevas fuerzas productivas, ayuda en la gestión racional de los bienes comunes, o un punto de partida para la reducción del tiempo de trabajo. No se trata de rechazar la IA o la robótica; se trata de disputar sus propósitos, su producción y su gobernanza.
            </blockquote>
            <p>La investigadora Paola Ricaurte, desde el feminismo decolonial, muestra, en la práctica, con el proyecto de <a href="https://archive.org/details/inteligencia-artificial-feminista" target="_blank" rel="noopener noreferrer">IA Feminista</a>, cómo se materializa esta apropiación de la IA para fines transformadores. Parte de su obra académica se ha centrado en señalar cómo la inteligencia artificial reproduce la colonialidad, el patriarcado, el racismo y el extractivismo digital. Sin embargo, en una <a href="https://www.youtube.com/watch?v=jFrm1TjzlSA&t=283s" target="_blank" rel="noopener noreferrer">entrevista</a> sobre la posibilidad de una IA Feminista, Ricaurte expresó que esta debe pensarse desde una perspectiva marxista, como si de tomar los medios de producción se tratase, "si nosotras somos las que podemos conseguir, tomar, diseñar, pensar, crear las herramientas en nuestros términos, con otros valores, que no sean los del capitalismo". La lucha por quién y cómo se crean y aplican las inteligencias artificiales no solo concierne a estados o grandes compañías, sino también a la apropiación social de la misma por comunidades, organizaciones sociales y movimientos.</p>
            <p>La divergencia estratégica entre los modelos de inteligencia artificial de Estados Unidos y China trasciende la clásica pregunta de quién va ganando la carrera. Refleja lógicas, estrategias y metas distintas. A grandes rasgos, mientras que el ecosistema norteamericano está conformado por arquitecturas cerradas, se centra en la innovación pura, alimenta un modelo de negocio basado en la financiarización, e impulsa la integración militar-industrial y el bombo publicitario, China ha apostado por una visión diferente. Bajo el principio de soberanía cibernética, el país asiático integra la IA en cadenas productivas reales, como manufactura y logística; pone el énfasis en la aplicación práctica a más ámbitos, como la salud o la educación, y despliega modelos mayoritariamente de código y pesos abiertos. Esta estrategia divergente responde a lógicas de acumulación y gobernanza diferentes. EE.UU. quiere consolidar un monopolio del poder algorítmico cada vez más militarizado, y ser el primero en alcanzar lo que el propio Sam Altman, CEO de OpenAI, considera la mercancía más valiosa de la historia: la <a href="https://www.science.org/doi/10.1126/science.ado7069" target="_blank" rel="noopener noreferrer">AGI</a> (la inteligencia artificial general).</p>
            <p>China, por su parte, tiene por objetivo fortalecer la autosuficiencia tecnológica y despliega ecosistemas abiertos orientados a la eficiencia y la reducción del precio por token de los modelos de IA, lo que entrega a los países del Sur Global alternativas para aplicar y usar sistemas de IA gratuitos o más asequibles en costes. Como argumenta la teórica <a href="https://www.bibliovault.org/BV.book.epl?ISBN=9780252082399" target="_blank" rel="noopener noreferrer">Yu Hong</a>, a diferencia del modelo occidental de desregulación corporativa, el Estado chino, en conjunción con las fuerzas del mercado y los intereses de clase, está construyendo y realineando activamente su sector digitalizado. En esta línea, como explica Hong, frente al modelo de Silicon Valley (donde el Estado opera como cliente y propulsor de monopolios privados), la plataformización en China está estrictamente subordinada a la planificación estatal, la seguridad nacional y los objetivos políticos de desarrollo industrial soberano, impidiendo que la racionalidad y el poder corporativo dominen el poder político. Sin embargo, esto no debe impulsarnos a magnificar acríticamente el ecosistema tecnológico chino, ya que como señalan Hong y la investigadora Kate Crawford, este genera lógicas similares de precarización laboral o extractivismo del capitalismo de plataforma.</p>
            <p>Pero la disputa por el Intelecto Computacional no se libra exclusivamente entre distintos modelos de IA, ni tan solo entre Big Tech y estados que defienden su soberanía digital. También se juega en otras dinámicas como la apropiación de la IA por parte de los movimientos populares, la lucha contra el extractivismo desaforado de los recursos planetarios, como ha mostrado Crawford en su libro <em>Atlas de IA</em> y en la organización de los trabajadores cognitivos de baja, media y alta cualificación. Se trata de una nueva clase trabajadora cognitiva computacional, desde los <a href="https://www.theguardian.com/technology/2023/aug/02/ai-chatbot-training-human-toll-content-moderator-meta-openai?utm_source=chatgpt.com" target="_blank" rel="noopener noreferrer">etiquetadores y moderadores de IA en Kenia</a>, pasando por los <a href="https://unionaid.org.nz/digital-workers-unite-to-protect-rights-as-ai-threatens-jobs/" target="_blank" rel="noopener noreferrer">trabajadores de call centers y BPO en Filipinas</a>, hasta los <a href="https://es.wired.com/articulos/los-trabajadores-de-google-deepmind-buscan-sindicalizarse-ante-el-uso-militar-de-la-ia?utm_source=chatgpt.com" target="_blank" rel="noopener noreferrer">investigadores de Google DeepMind</a> que se sindicalizan contra el uso militar de la IA.</p>
            <p>En los movimientos populares del Sur Global, la reapropiación social de la IA es una tendencia creciente. Recientemente, en mayo de 2026, el <a href="https://mst.org.br/" target="_blank" rel="noopener noreferrer">Movimiento Sin Tierra (MST)</a> de Brasil lanzó <a href="https://mst.org.br/2025/11/06/conheca-a-iaraa-inteligencia-artificial-da-reforma-agraria-e-agroecologia/" target="_blank" rel="noopener noreferrer"><strong>IARAA</strong></a>, una inteligencia artificial propia entrenada para asistir en la agroecología y la reforma agraria popular, demostrando que la tecnología puede subordinarse a las necesidades de la clase trabajadora rural. En una lógica similar, <a href="https://iafeminista.lat/historia/" target="_blank" rel="noopener noreferrer">la Red Feminista de IA en América Latina y el Caribe</a>, y proyectos como <a href="https://www.fsmi.in/" target="_blank" rel="noopener noreferrer">Datos contra el Feminicidio</a>, <a href="https://www.tierracomun.net/" target="_blank" rel="noopener noreferrer">Tierra en común</a>, o las redes transhackfeministas como <a href="https://codigonaobinario.org/" target="_blank" rel="noopener noreferrer">Código No Binario</a> politizan los algoritmos para combatir la violencia patriarcal y el colonialismo de datos. En la India, <a href="https://www.fsmi.in/" target="_blank" rel="noopener noreferrer">el movimiento del software libre</a> combate la instalación del control biométrico obligatorio y años atrás derrotó a Meta en su plan para capturar el internet del país más poblado del mundo, mientras que asambleas vecinales, desde <a href="https://mosacatchile.cl/" target="_blank" rel="noopener noreferrer">Chile</a> hasta <a href="https://amnistia.org.uy/campana-ciudadana-para-exigir-mayores-estudios-a-google-por-su-proyecto-de-datacenter/" target="_blank" rel="noopener noreferrer">Uruguay</a>, logran frenar la instalación de megaproyectos extractivistas de centros de datos.</p>
            <p>Simultáneamente, en el Norte Global, en los últimos años se han activado campañas tecnopolíticas como <a href="https://techforpalestine.org/" target="_blank" rel="noopener noreferrer">Tech For Palestine</a>; trabajadores de Amazon y Google organizaron huelgas bajo la campaña <a href="https://www.notechforapartheid.com/" target="_blank" rel="noopener noreferrer">No Tech for Apartheid</a>, denunciando la colaboración con el proyecto <a href="https://es.wired.com/articulos/lazos-ocultos-entre-ejercito-israeli-y-proyecto-nimbus-google-y-amazon" target="_blank" rel="noopener noreferrer">Nimbus</a> y se han multiplicado protestas e iniciativas contra Palantir, como la campaña <a href="https://purgepalantir.com/" target="_blank" rel="noopener noreferrer">Purge Palantir</a>, y acciones contra la militarización de la IA, su uso autoritario y de vigilancia. En el plano de la construcción de alternativas tecnológicas, podemos destacar proyectos como <a href="https://joinmastodon.org/es" target="_blank" rel="noopener noreferrer">Mastodon</a> y Signal, el ecosistema del <a href="https://jointhefediverse.net/" target="_blank" rel="noopener noreferrer">Fediverso</a>, o la plataforma de participación e inteligencia colectiva <a href="https://www.researchgate.net/publication/365892044_Desplazar_los_ejes_alternativas_tecnologicas_derechos_humanos_y_sociedad_civil_a_principios_del_siglo_XXI" target="_blank" rel="noopener noreferrer">Decidim</a> (comunitaria y de código libre y abierto), que se ha convertido en un referente internacional de procesos de democracia participativa. Estos proyectos y movimientos, aún fragmentados, muestran que la intersección entre ellos, en términos de derechos laborales, justicia ambiental y la construcción de alternativas, es una piedra angular para que la revolución tecnológica no quede capturada bajo el tecnoimperialismo, ni gestionada exclusivamente por un puñado de tecnoligarcas.</p>
          </ArticleSection>

          {/* Infografía: Stack del Intelecto Computacional */}
          <figure 
            className="my-16 -mx-4 sm:-mx-6 lg:-mx-16 cursor-pointer group"
            onClick={() => openLightbox("/manus-storage/stack_intelecto_1da56d9f.png", "Stack del Intelecto Computacional")}
          >
            <img 
              src="/manus-storage/stack_intelecto_1da56d9f.png" 
              alt="Stack del Intelecto Computacional"
              className="w-full rounded-sm transition-transform duration-200 group-hover:scale-[1.005] shadow-lg"
            />
            <figcaption className="text-center text-sm text-muted-foreground mt-4 font-mono">
              Fig. 3 — Stack del Intelecto Computacional: las 7 capas de la infraestructura cognitiva
            </figcaption>
          </figure>

          {/* Infografía: Red Tecnopolítica */}
          <figure 
            className="my-16 -mx-4 sm:-mx-6 lg:-mx-16 cursor-pointer group"
            onClick={() => openLightbox("/manus-storage/red_tecnopolitica_c674efbb.png", "Red Tecnopolítica por la Soberanía Digital")}
          >
            <img 
              src="/manus-storage/red_tecnopolitica_c674efbb.png" 
              alt="Red Tecnopolítica por la Soberanía Digital"
              className="w-full rounded-sm transition-transform duration-200 group-hover:scale-[1.005] shadow-lg"
            />
            <figcaption className="text-center text-sm text-muted-foreground mt-4 font-mono">
              Fig. 4 — Red Tecnopolítica por la Soberanía Digital
            </figcaption>
          </figure>

          {/* ===================== SECCIÓN VI ===================== */}
          <ArticleSection id="brujula-estrategica" number="VI" title="La Doble Revolución como brújula estratégica">
            <p>La Doble Revolución es un diagnóstico de época que pretende funcionar como una <strong>brújula estratégica</strong> para orientarse en las próximas décadas. Aspira a funcionar como un mapa de coordenadas para leer las tendencias históricas centrales en el sistema-mundo: la convergencia entre la revolución tecnológica de la inteligencia artificial y la revolución geopolítica de la transición de poder mundial. Ambas se bifurcan de forma antagónica.</p>
            <p>En un lado se sitúa el <ConceptTag term="hiper-imperialismo" glossaryId="hiper-imperialismo" /> estadounidense, como potencia en declive que militariza la geopolítica y la inteligencia artificial. En el lado contrario, la Mayoría Global Multipolar (estados, bloques regionales y movimientos populares del Sur Global junto a desertores críticos del Norte Global), que resisten a los ataques y agresiones, diseñan arquitecturas financieras alternativas, construyen soberanías tecnológicas y modelos abiertos para quebrar la dependencia digital.</p>
            <blockquote>
              Reconociendo este antagonismo, debemos preguntarnos hacia el futuro: ¿será esta Doble Revolución dominada por el tecnoimperialismo, o hegemonizada por las potencias multipolares? Y, más allá, ¿serán las fuerzas populares protagonistas de una transformación radical de las relaciones de poder capitalista?
            </blockquote>
            <p>El resultado de la Doble Revolución es incierto, dependerá de las correlaciones de fuerzas de los distintos actores geopolíticos, de la capacidad de articulación de las luchas con nuevos proyectos emancipadores y de quién y cómo se controle la revolución tecnológica del Intelecto Computacional.</p>
            <p>Hobsbawm mostró cómo la Doble Revolución del siglo XIX creó nuevas clases sociales y nuevos sujetos políticos. Pero ¿cuáles serán los sujetos políticos de la doble revolución del siglo XXI? Esta pregunta exige una respuesta honesta: aún no están plenamente constituidos, pero, aunque sea de forma incipiente y aislada, gran parte de sus componentes ya están sobre la mesa. La izquierda mundial padece tanto de una hiperfragmentación como de una falta de articulación estratégica internacional, de una desconexión de su base social altamente precarizada tras años de hegemonía neoliberal, e incluso de una falta de comprensión del alcance de la revolución tecnológica. La fragmentación temática, geográfica e ideológica encierra las luchas en agendas parciales y desconectadas entre sí.</p>
            <p>A pesar de eso, la recomposición de un bloque histórico transnacional a la altura del desafío de la Doble Revolución –encarnado en la Mayoría Global Multipolar– ya está en marcha. Esta recomposición no pasará por la uniformidad ideológica, identitaria o religiosa, sino por la construcción de banderas unitarias que articulen la diversidad. Para ello, resulta clave reimaginar espacios masivos de protesta y articulación internacional a partir de la experiencia de los ciclos políticos anteriores, adaptándolos a las condiciones actuales descritas.</p>
            <blockquote>
              "Tenemos que derrotar a Netanyahu y a Trump. Tenemos que derrocar a los criminales de guerra. Necesitamos derrotar al complejo militar industrial que se beneficia de la guerra. A las grandes tecnológicas que quieren controlar nuestras vidas. Necesitamos construir un futuro diferente."
              <cite className="block text-sm text-primary mt-2 not-italic font-mono">— Tiago Ávila</cite>
            </blockquote>
            <p>La unidad estratégica se construye en torno a estos elementos y frente a los enemigos principales que la fase histórica impone. Este llamado podría traducirse en un futuro donde la lucha de clases y la lucha de los pueblos, el combate de las jerarquías Norte-Sur, el antiimperialismo, la <ConceptTag term="soberanía digital" glossaryId="soberania-digital" /> y la soberanía de la IA se funden con la defensa de la reproducción de la vida y del planeta, en un mismo proyecto emancipador que sea determinante en la transición sistémica. Un reto enorme para las próximas décadas. No basta con anunciar el colapso del viejo mundo occidental, ni siquiera basta con imaginar el fin del capitalismo. Se trata de empujar y radicalizar el mundo nuevo multipolar que ya está en marcha, para que la Doble Revolución del siglo XXI se despliegue con toda su fuerza emancipadora.</p>
            <p className="text-right text-muted-foreground mt-12 font-mono text-sm">Barcelona. 15/05/2026</p>
          </ArticleSection>

          {/* Infografía: Matriz síntesis */}
          <figure 
            className="my-16 -mx-4 sm:-mx-6 lg:-mx-16 cursor-pointer group"
            onClick={() => openLightbox("/manus-storage/matriz_sintesis_5f304d60.png", "Doble Revolución: Matriz de síntesis")}
          >
            <img 
              src="/manus-storage/matriz_sintesis_5f304d60.png" 
              alt="Doble Revolución: Matriz de síntesis"
              className="w-full rounded-sm transition-transform duration-200 group-hover:scale-[1.005] shadow-lg"
            />
            <figcaption className="text-center text-sm text-muted-foreground mt-4 font-mono">
              Fig. 5 — La Doble Revolución como brújula estratégica: Matriz de síntesis
            </figcaption>
          </figure>

          {/* Glosario */}
          <Glossary />

        </main>

        <Footer />
      </div>

      {/* Lightbox */}
      {lightboxImage && (
        <ImageLightbox 
          src={lightboxImage} 
          alt={lightboxAlt} 
          onClose={() => setLightboxImage(null)} 
        />
      )}
    </div>
  );
}
